### ISSUE TITLE
wallet won't run on Win8.1 x64 - "illegal instruction"

### ISSUE THREAD

**Issue by BTCUSD** [beam-mw/beam#6]
User Mini Dump File: Only registers, stack and portions of memory are available

Symbol search path is: srv*
Executable search path is: 
Windows 8.1 Version 9600 MP (2 procs) Free x64
Product: WinNt, suite: SingleUserTS Personal
6.3.9600.17031 (winblue_gdr.140221-1952)
Machine Name:
Debug session time: Wed Sep 26 20:27:21.000 2018 
System Uptime: not available
Process Uptime: 0 days 0:00:10.000
......................................
This dump file has an exception of interest stored in it.
The stored exception information can be accessed via .ecxr.
(990.814): Illegal instruction - code c000001d (first/second chance not available)
ntdll!NtWaitForMultipleObjects+0xa:
00007ff9`f4c8b2ba c3              ret
0:000> .ecxr
*** WARNING: Unable to verify checksum for Beam Wallet.exe
*** ERROR: Module load completed but symbols could not be loaded for Beam Wallet.exe
rax=00000019ad939680 rbx=00007ff665ccc7e0 rcx=0000000000000009
rdx=0000000000001000 rsi=000000000000007f rdi=000000000000009d
rip=00007ff663bdec0e rsp=00000019ad86fa50 rbp=0000000000000000
 r8=0000000000000080  r9=0000000000000001 r10=00000019ad93bff0
r11=0000000000000000 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
Beam_Wallet+0x8ec0e:
00007ff6`63bdec0e c5f9efc0        vpxor   xmm0,xmm0,xmm0
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

GetUrlPageData2 (WinHttp) failed: 12002.

KEY_VALUES_STRING: 1

TIMELINE_ANALYSIS: 1

Timeline: !analyze.Start
    Name: <blank>
    Time: 2018-09-26T17:31:44.717Z
    Diff: 263717 mSec

Timeline: Dump.Current
    Name: <blank>
    Time: 2018-09-26T17:27:21.0Z
    Diff: 0 mSec

Timeline: Process.Start
    Name: <blank>
    Time: 2018-09-26T17:27:11.0Z
    Diff: 10000 mSec

DUMP_CLASS: 2

DUMP_QUALIFIER: 400

CONTEXT:  (.ecxr)
rax=00000019ad939680 rbx=00007ff665ccc7e0 rcx=0000000000000009
rdx=0000000000001000 rsi=000000000000007f rdi=000000000000009d
rip=00007ff663bdec0e rsp=00000019ad86fa50 rbp=0000000000000000
 r8=0000000000000080  r9=0000000000000001 r10=00000019ad93bff0
r11=0000000000000000 r12=0000000000000000 r13=0000000000000000
r14=0000000000000000 r15=0000000000000000
iopl=0         nv up ei pl nz na pe nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010202
Beam_Wallet+0x8ec0e:
00007ff6`63bdec0e c5f9efc0        vpxor   xmm0,xmm0,xmm0
Resetting default scope

FAULTING_IP: 
Beam_Wallet+8ec0e
00007ff6`63bdec0e c5f9efc0        vpxor   xmm0,xmm0,xmm0

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ff663bdec0e (Beam_Wallet+0x000000000008ec0e)
   ExceptionCode: c000001d (Illegal instruction)
  ExceptionFlags: 00000000
NumberParameters: 0

DEFAULT_BUCKET_ID:  ILLEGAL_INSTRUCTION

PROCESS_NAME:  Beam Wallet.exe

ERROR_CODE: (NTSTATUS) 0xc000001d - {EXCEPTION}  Illegal Instruction  An attempt was made to execute an illegal instruction.

EXCEPTION_CODE: (NTSTATUS) 0xc000001d - {EXCEPTION}  Illegal Instruction  An attempt was made to execute an illegal instruction.

EXCEPTION_CODE_STR:  c000001d

WATSON_BKT_PROCSTAMP:  5ba35fee

WATSON_BKT_PROCVER:  0.0.1.0

WATSON_BKT_MODULE:  Beam Wallet.exe

WATSON_BKT_MODSTAMP:  5ba35fee

WATSON_BKT_MODOFFSET:  8ec0e

WATSON_BKT_MODVER:  0.0.1.0

BUILD_VERSION_STRING:  6.3.9600.17031 (winblue_gdr.140221-1952)

MODLIST_WITH_TSCHKSUM_HASH:  f6e997e69f9af1457b03136a3800845c66f71a52

MODLIST_SHA1_HASH:  5b42c3bdceb1ce339bca0c8790890d99d9ca84ce

NTGLOBALFLAG:  0

PROCESS_BAM_CURRENT_THROTTLED: 0

PROCESS_BAM_PREVIOUS_THROTTLED: 0

APPLICATION_VERIFIER_FLAGS:  0

DUMP_FLAGS:  94

DUMP_TYPE:  1

ANALYSIS_SESSION_HOST:  NIKE

ANALYSIS_SESSION_TIME:  09-26-2018 20:31:44.0717

ANALYSIS_VERSION: 10.0.17134.12 amd64fre

PROBLEM_CLASSES: 

    ID:     [0n317]
    Type:   [@APPLICATION_FAULT_STRING]
    Class:  Primary
    Scope:  DEFAULT_BUCKET_ID (Failure Bucket ID prefix)
            BUCKET_ID
    Name:   Omit
    Data:   Add
            String: [ILLEGAL_INSTRUCTION]
    PID:    [Unspecified]
    TID:    [Unspecified]
    Frame:  [0]

BUGCHECK_STR:  ILLEGAL_INSTRUCTION

PRIMARY_PROBLEM_CLASS:  ILLEGAL_INSTRUCTION

LAST_CONTROL_TRANSFER:  from 00007ff664a0c67b to 00007ff663bdec0e

STACK_TEXT:  
00000019`ad86fa50 00007ff6`64a0c67b : 00007ff6`65ccc7e0 00000000`0000007d 00000000`0000009d 00000000`0000007a : Beam_Wallet+0x8ec0e
00000019`ad86fa90 00007ff6`649c5594 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : Beam_Wallet+0xebc67b
00000019`ad86fac0 00007ff9`f2b816ad : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : Beam_Wallet+0xe75594
00000019`ad86fb00 00007ff9`f4c634a5 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : kernel32!BaseThreadInitThunk+0xd
00000019`ad86fb30 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!RtlUserThreadStart+0x1d

FAILED_INSTRUCTION_ADDRESS: 
Beam_Wallet+8ec0e
00007ff6`63bdec0e c5f9efc0        vpxor   xmm0,xmm0,xmm0

THREAD_SHA1_HASH_MOD_FUNC:  9ee793a5a7684f8cd9214dfcc13cd57e27b2f4f3

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  090db0f2edcf4c410b3a4d4e61db043b66e78a4c

THREAD_SHA1_HASH_MOD:  cf9629006ca40794dc89cc129c042551b5c33ff2

FOLLOWUP_IP: 
Beam_Wallet+8ec0e
00007ff6`63bdec0e c5f9efc0        vpxor   xmm0,xmm0,xmm0

FAULT_INSTR_CODE:  c0eff9c5

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  Beam_Wallet+8ec0e

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: Beam_Wallet

IMAGE_NAME:  Beam_Wallet.exe

DEBUG_FLR_IMAGE_TIMESTAMP:  5ba35fee

STACK_COMMAND:  ~0s ; .ecxr ; kb

BUCKET_ID:  ILLEGAL_INSTRUCTION_BAD_IP_Beam_Wallet+8ec0e

FAILURE_EXCEPTION_CODE:  c000001d

FAILURE_IMAGE_NAME:  Beam_Wallet.exe

BUCKET_ID_IMAGE_STR:  Beam_Wallet.exe

FAILURE_MODULE_NAME:  Beam_Wallet

BUCKET_ID_MODULE_STR:  Beam_Wallet

FAILURE_FUNCTION_NAME:  Unknown

BUCKET_ID_FUNCTION_STR:  Unknown

BUCKET_ID_OFFSET:  8ec0e

BUCKET_ID_MODTIMEDATESTAMP:  5ba35fee

BUCKET_ID_MODCHECKSUM:  0

BUCKET_ID_MODVER_STR:  0.0.1.0

BUCKET_ID_PREFIX_STR:  ILLEGAL_INSTRUCTION_BAD_IP_

FAILURE_PROBLEM_CLASS:  ILLEGAL_INSTRUCTION

FAILURE_SYMBOL_NAME:  Beam_Wallet.exe!Unknown

FAILURE_BUCKET_ID:  ILLEGAL_INSTRUCTION_c000001d_Beam_Wallet.exe!Unknown

WATSON_STAGEONE_URL:  http://watson.microsoft.com/StageOne/Beam Wallet.exe/0.0.1.0/5ba35fee/Beam Wallet.exe/0.0.1.0/5ba35fee/c000001d/0008ec0e.htm?Retriage=1

TARGET_TIME:  2018-09-26T17:27:21.000Z

OSBUILD:  9600

OSSERVICEPACK:  17056

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  768

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 8.1

OSEDITION:  Windows 8.1 WinNt SingleUserTS Personal

USER_LCID:  0

OSBUILD_TIMESTAMP:  2014-03-20 03:17:16

BUILDDATESTAMP_STR:  140221-1952

BUILDLAB_STR:  winblue_gdr

BUILDOSVER_STR:  6.3.9600.17031

ANALYSIS_SESSION_ELAPSED_TIME:  c8be

ANALYSIS_SOURCE:  UM

FAILURE_ID_HASH_STRING:  um:illegal_instruction_c000001d_beam_wallet.exe!unknown

FAILURE_ID_HASH:  {bcab0329-4f99-837f-7af1-cb6ce1a7624f}

Followup:     MachineOwner

**Comment by art-gor** [comment]
"illegal instruction" raised because the binaries were built against fresh instruction set (sse4.2 avx and so on) and won't work on older CPUs. Going to workaround this issue

**Comment by gingervik** [comment]
fixed in Testnet 2
wallet ver 3005
