### ISSUE TITLE
Balance stuck at 'Unconfirmed'

### ISSUE THREAD

**Issue by xempew** [beam-mw/beam#7]
[beam v1.0.2516 windows report.zip](https://github.com/beam-mw/beam/files/2439928/beam.v1.0.2516.windows.report.zip)

Problem description:

Sent myself a few transactions (coins that I mined myself), and now the wallet shows an Unconfirmed balance of 79.999999, and seems to be stuck at this for many days.

Please find attached the wallet log archive.

All my best,
xempew

**Comment by gingervik** [comment]
Fixed in testnet 2
wallet ver 3005
